{
 "title": "Personal Finances",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "fire_annual_factor", "query": "25" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "currency",
    "query": {
     "query": "label_values(hledger_fx_rate,currency)"
    }
   },
   { "name": "agg_window", "label": "aggregation window (days)", "query": "365" }
  ]
 },
 "panels": [
  {
   "title": "Net Worth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hledger_balance{account=\"assets\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n+ on(target_currency)\r\nsum(hledger_balance{account=\"liabilities\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Savings Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "# saved income\r\n(\r\n    sum(hledger_monthly_decrease{account=\"income\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_monthly_increase{account=\"expenses\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    # ignore pension contributions (assumes pensions only go up - include 'decrease' as well to handle January roll-over)\r\n    - on(target_currency)\r\n    (\r\n        sum(hledger_monthly_increase{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency) -\r\n        sum(hledger_monthly_decrease{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    )\r\n)\r\n\r\n/ on(target_currency)\r\n\r\n# net income\r\n(\r\n    sum(hledger_monthly_decrease{account=\"income\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_monthly_increase{account=\"expenses:gross\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    # as above\r\n    - on(target_currency)\r\n    (\r\n        sum(hledger_monthly_increase{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency) -\r\n        sum(hledger_monthly_decrease{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    )\r\n)"
    }
   ]
  },
  {
   "title": "Short Runway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# total available cash and emergency fund\r\n(\r\n    sum(hledger_balance{account=\"assets:cash\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    + on (target_currency)\r\n    sum(hledger_balance{account=\"assets:investments:nsi:premium_bonds:emergency\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n)\r\n\r\n/ on (target_currency)\r\n\r\n# average daily expense\r\n(\r\n    (\r\n        sum(hledger_balance{account=\"expenses\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"expenses\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"expenses:gross\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        + on(target_currency)\r\n        sum(hledger_balance{account=\"expenses:gross\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    ) / $agg_window\r\n)"
    }
   ]
  },
  {
   "title": "Long Runway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hledger_balance{account=\"assets\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n/ on (target_currency)\r\n\r\n# average daily expense\r\n(\r\n    (\r\n        sum(hledger_balance{account=\"expenses\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"expenses\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"expenses:gross\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        + on(target_currency)\r\n        sum(hledger_balance{account=\"expenses:gross\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    ) / $agg_window\r\n)"
    }
   ]
  },
  {
   "title": "House Deposit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hledger_balance{account=\"assets:investments:ajbell:lisa\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n+ on(target_currency)\r\nsum(hledger_balance{account=\"assets:investments:nsi:premium_bonds:house\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "FIRE Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# all assets (sans pension)\r\n(\r\n    sum(hledger_balance{account=\"assets\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_balance{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n)\r\n\r\n/ on(target_currency)\r\n\r\n# FIRE number\r\n(\r\n    (\r\n        sum(hledger_balance{account=\"expenses\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"expenses\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"expenses:gross\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        + on(target_currency)\r\n        sum(hledger_balance{account=\"expenses:gross\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    ) / $agg_window * 365 * $fire_annual_factor\r\n)"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hledger_transactions_total) without(status)"
    }
   ]
  },
  {
   "title": "Assets (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "sum(hledger_balance{account=\"assets:receivable\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Receivable",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(hledger_balance{account=\"assets:investments:nsi:premium_bonds\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Premium Bonds"
    },
    {
     "expr": "sum(hledger_balance{account=\"assets:investments\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n- on(target_currency)\r\nsum(hledger_balance{account=\"assets:investments:nsi:premium_bonds\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Funds"
    },
    {
     "expr": "sum(hledger_balance{account=\"assets:cash\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Cash"
    },
    {
     "expr": "(\r\n    # average daily income\r\n    (\r\n        sum(hledger_balance{account=\"income\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"income\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"income:gift\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        + on(target_currency)\r\n        sum(hledger_balance{account=\"income:gift\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    ) / $agg_window * -1\r\n\r\n    # age/10 years worth\r\n    * 365 * ignoring(unit) quantified_self_age{unit=\"years\"} / 10\r\n) / 2\r\n\r\n# ignore gifted income\r\n- on(target_currency)\r\nsum(hledger_balance{account=\"income:gift\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n\r\n# add (subtract) liabilities, other than student loan\r\n- on(target_currency)\r\nsum(hledger_balance{account=\"liabilities\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n+ on(target_currency)\r\nsum(hledger_balance{account=\"liabilities:loan:slc\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)",
     "legendFormat": "Target: AAW"
    },
    {
     "expr": "(\r\n    # average daily income\r\n    (\r\n        sum(hledger_balance{account=\"income\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"income\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        - on(target_currency)\r\n        sum(hledger_balance{account=\"income:gift\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n        + on(target_currency)\r\n        sum(hledger_balance{account=\"income:gift\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    ) / $agg_window * -1\r\n\r\n    # age/10 years worth\r\n    * 365 * ignoring(unit) quantified_self_age{unit=\"years\"} / 10\r\n) * 2\r\n\r\n# ignore gifted income\r\n- on(target_currency)\r\nsum(hledger_balance{account=\"income:gift\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n\r\n# add (subtract) liabilities, other than student loan\r\n- on(target_currency)\r\nsum(hledger_balance{account=\"liabilities\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n+ on(target_currency)\r\nsum(hledger_balance{account=\"liabilities:loan:slc\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)",
     "legendFormat": "Target: PAW"
    },
    {
     "expr": "# average daily expense\r\n(\r\n    sum(hledger_balance{account=\"expenses\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_balance{account=\"expenses\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_balance{account=\"expenses:gross\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    + on(target_currency)\r\n    sum(hledger_balance{account=\"expenses:gross\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n) / $agg_window\r\n\r\n# $fire_annual_factor years worth\r\n* 365 * $fire_annual_factor",
     "legendFormat": "Target: FIRE"
    }
   ]
  },
  {
   "title": "Current Allocation",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hledger_balance{account=\"assets:cash\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Cash"
    },
    {
     "expr": "sum(hledger_balance{account=\"assets:investments\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n- on(target_currency)\r\nsum(hledger_balance{account=\"assets:investments:nsi:premium_bonds\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Funds"
    },
    {
     "expr": "sum(hledger_balance{account=\"assets:investments:nsi:premium_bonds\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Premium Bonds"
    },
    {
     "expr": "sum(hledger_balance{account=\"assets:receivable\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Receivable"
    }
   ]
  },
  {
   "title": "Safe Withdrawal Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n    sum(hledger_balance{account=\"assets\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_balance{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n) * 0.04",
     "legendFormat": "4.0%"
    },
    {
     "expr": "(\r\n    sum(hledger_balance{account=\"assets\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_balance{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n) * 0.035",
     "legendFormat": "3.5%"
    },
    {
     "expr": "(\r\n    sum(hledger_balance{account=\"assets\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_balance{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n) * 0.03",
     "legendFormat": "3.0%"
    },
    {
     "expr": "(\r\n    sum(hledger_balance{account=\"assets\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_balance{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n) * 0.025",
     "legendFormat": "2.5%"
    },
    {
     "expr": "(\r\n    sum(hledger_balance{account=\"expenses\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_balance{account=\"expenses\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_balance{account=\"expenses:gross\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n    + on(target_currency)\r\n    sum(hledger_balance{account=\"expenses:gross\"} offset ${agg_window}d * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by (target_currency)\r\n) / $agg_window * 365",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Cleared",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hledger_transactions_total{status=\"cleared\"}"
    }
   ]
  },
  {
   "title": "Uncleared",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hledger_transactions_total{status=\"pending\"}"
    }
   ]
  },
  {
   "title": "Bookkeeping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hledger_transactions_total{status=\"bookkeeping\"}"
    }
   ]
  },
  {
   "title": "Bookkeeping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hledger_transactions_total{status=\"bookkeeping\"}\r\n/ ignoring(status)\r\nsum(hledger_transactions_total) without(status)"
    }
   ]
  },
  {
   "title": "Net Worth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "sum(hledger_balance{account=\"assets\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Total Assets"
    },
    {
     "expr": "sum(hledger_balance{account=\"liabilities\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Total Liabilities"
    },
    {
     "expr": "sum(hledger_balance{account=\"assets\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n+ on(target_currency)\r\nsum(hledger_balance{account=\"liabilities\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "Credit Card",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "sum(hledger_balance{account=\"assets:cash:nationwide:flexdirect:pending:amex\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Put Aside"
    },
    {
     "expr": "sum(hledger_balance{account=\"liabilities:creditcard:amex\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Liability"
    },
    {
     "expr": "sum(hledger_balance{account=\"assets:cash:nationwide:flexdirect:pending:amex\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n+ on(target_currency)\r\nsum(hledger_balance{account=\"liabilities:creditcard:amex\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Delta"
    }
   ]
  },
  {
   "title": "Cash Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "sum(hledger_monthly_decrease{account=\"income\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n- on(target_currency)\r\nsum(hledger_monthly_increase{account=\"expenses:gross\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n\r\n# ignore pension contributions (assumes pensions only go up - include 'decrease' as well to handle January roll-over)\r\n- on(target_currency)\r\n(\r\n    sum(hledger_monthly_increase{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency) -\r\n    sum(hledger_monthly_decrease{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n)",
     "legendFormat": "Income (net)"
    },
    {
     "expr": "sum(hledger_monthly_increase{account=\"expenses\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n- on(target_currency)\r\nsum(hledger_monthly_increase{account=\"expenses:gross\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)",
     "legendFormat": "Expenses"
    },
    {
     "expr": "# saved income\r\n(\r\n    sum(hledger_monthly_decrease{account=\"income\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_monthly_increase{account=\"expenses\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    # ignore pension contributions (assumes pensions only go up - include 'decrease' as well to handle January roll-over)\r\n    - on(target_currency)\r\n    (\r\n        sum(hledger_monthly_increase{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency) -\r\n        sum(hledger_monthly_decrease{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    )\r\n)\r\n\r\n/ on(target_currency)\r\n\r\n# net income\r\n(\r\n    sum(hledger_monthly_decrease{account=\"income\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    - on(target_currency)\r\n    sum(hledger_monthly_increase{account=\"expenses:gross\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    # as above\r\n    - on(target_currency)\r\n    (\r\n        sum(hledger_monthly_increase{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency) -\r\n        sum(hledger_monthly_decrease{account=\"assets:pension\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)\r\n    )\r\n)",
     "legendFormat": "Savings Rate"
    }
   ]
  },
  {
   "title": "Gift",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:gift\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Health",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:health\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Household",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:household\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Patreon",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:patreon\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Phone",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:phone\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Protonmail",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:protonmail\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Rent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:rent\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Travel",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:travel\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Utilities",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:utilities\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Web",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(hledger_balance{account=~\".*:saved:web\"}) by (currency) * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "AJ Bell Dealing Account",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hledger_balance{account=\"assets:investments:ajbell:dealing\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Fidelity Cash Management Account",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hledger_balance{account=\"assets:investments:fidelity:management\"} * on(currency) hledger_fx_rate{target_currency=\"$currency\"}) by(target_currency)"
    }
   ]
  },
  {
   "title": "Market Prices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Euro Unit Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "targets": [
      {
       "expr": "hledger_fx_rate{currency=\"EUR\",target_currency=\"$currency\"}",
       "legendFormat": "Value of 1 {{currency}} in {{target_currency}}"
      }
     ]
    },
    {
     "title": "US Dollar Unit Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "targets": [
      {
       "expr": "hledger_fx_rate{currency=\"USD\",target_currency=\"$currency\"}",
       "legendFormat": "Value of 1 {{currency}} in {{target_currency}}"
      }
     ]
    },
    {
     "title": "Japanese Yen Unit Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "targets": [
      {
       "expr": "hledger_fx_rate{currency=\"JPY\",target_currency=\"$currency\"}",
       "legendFormat": "Value of 1 {{currency}} in {{target_currency}}"
      }
     ]
    },
    {
     "title": "Vanguard LifeStrategy 100% (Acc) Fund Unit Value",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "targets": [
      {
       "expr": "hledger_fx_rate{currency=\"VANEA\",target_currency=\"$currency\"}",
       "legendFormat": "Value of 1 {{currency}} in {{target_currency}}"
      }
     ]
    }
   ]
  }
 ]
}